// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdoaokiaqtyozskobbtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkb2Fva2lhcXR5b3pza29iYnRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4NTgwNDUsImV4cCI6MjA3NjQzNDA0NX0.UOYcx-KGwqMACKFfptPUWtXUTDdl7_2T8sx3RJcTrdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});